date: "2020-01-02"
detector: "e2w_in"
path: "data/calibration_intermediate_data/"
pathout: "data/calibration_data/"
pathin: "data/daily_splitted_data/"
iteration: 50
init_number: 0
network_file: "data/map/Hornsgatan.net.xml"
base_estimator: "GP"
acq_func: "LCB"
n_initial_points: 5
