date: "2020-01-01"
detector: "e2w_out"
path: "data/calibration_intermediate_data/"
pathout: "data/calibration_data/"
pathin: "data/daily_splitted_data/"
iteration: 50
init_number: 0
network_file: "data/map/Hornsgatan.net.xml"
hornsgatan_home: "/home/kaveh/Hornsgatan/"
