date: "2024-02-19"
detector: "e2w_out"
path: "data/calibration_intermediate_data/"
pathout: "data/calibration_data/"
pathin: "data/daily_splitted_data/"
iteration: 40
init_number: -1
network_file: "data/map/Hornsgatan.net.xml"
base_estimator: "GP"
acq_func: "LCB"
n_initial_points: 5
no_speed: false
name: "GP_LCB_50_5"
